version: "3.8"

services:
  user-service:
    build: .
    container_name: user-service
    ports:
      - "5000:5000"
    environment:
      - FLASK_APP=run.py
      - DATABASE_URL=postgresql://postgres:postgres@user-service-postgres:5432/users
    depends_on:
      user-service-postgres:
        condition: service_healthy
    networks:
      - user-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  user-service-postgres:
    image: postgres:13
    container_name: user-service-postgres
    environment:
      - POSTGRES_DB=users
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - user-network
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres"]
      interval: 10s
      timeout: 5s
      retries: 3

networks:
  user-network:
    driver: bridge

volumes:
  postgres_data:
